### PR TITLE
update socketio library version

### PR DESCRIPTION
**Pull request by domspad**
Was getting error `Uncaught TypeError: Cannot read property 'onClose' of null` in the console when trying to connect as a client. This fixes it.

### CODE REVIEW

**Comment by mattmakai** [comment]
does flask-socketio now work with versions greater than 0.96? previously there was an issue where the 1.0+ release of socketio wouldn't work properly

**Comment by domspad** [comment]
Yep, probably due to the updates to `flask_socketio`

**Comment by mattmakai** [comment]
oh awesome! what version of flask-socketio should be in the [requirements.txt](https://github.com/makaimc/python-websockets-example/blob/master/requirements.txt) file so I can test this out?

**Comment by domspad** [comment]
looks like `2.4` 
https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/setup.py#L12

**Comment by mattmakai** [comment]
Cool, looks good to me, thanks @domspad!

**Pull request merged**
